### PR TITLE
Create ruby.yml

### PR DESCRIPTION
**Pull request by semmons99**

### CODE REVIEW

**Comment by antstorm** [comment]
@semmons99 thoughts on squashing PRs when merging? Quite a lot of noise in the commit messages otherwise

**Comment by semmons99** [comment]
@antstorm I personally do not worry about a clean commit history. I find it is better for teaching and training to so the full creative process and not a modified end result.

**Comment by antstorm** [comment]
@semmons99 it does however make it difficult to build a changelog out of commits and unfortunately makes others question credibility (speaking from experience here)

**Comment by semmons99** [comment]
The first is totally valid and I muscle I have not flexed in quite some time. Thanks for reminding me. I will start considering this again when making public repo commits.

I will throw down with anyone who questions someone's credibility based on their commit history 💪 😎

**Comment by antstorm** [comment]
@semmons99 thank you 👍 😃

**Pull request merged**
