### PR TITLE
bump money to 6.6

### PR DESCRIPTION
**Pull request by tg0**

### CODE REVIEW

**Comment by semmons99** [comment]
thanks!

**Comment by lucascaton** [comment]
It fixes #398.

**Comment by lucascaton** [comment]
Hey @semmons99, could you please bump money-rails version to add this change? Thanks :smile:

**Comment by semmons99** [comment]
Have a couple more patches being talked about. Let's aim for a Jan 1 release.

**Comment by richardvenneman** [comment]
Any news on the release of a new version? :pray:

**Comment by semmons99** [comment]
Sorry, kept having patches roll in. I promise a Friday release.

- shane

**Pull request merged**
