### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by semmons99**

### CODE REVIEW

**Comment by semmons99** [comment]
@antstorm would you approve so we can release a new version please?

**Comment by TigerWolf** [comment]
Is there a changelog for this version?

**Comment by semmons99** [comment]
looks like we failed @TigerWolf . would you mind going through the commits and creating a PR with them?

**Comment by TigerWolf** [comment]
> looks like we failed @TigerWolf . would you mind going through the commits and creating a PR with them?

660

**Pull request merged**
