### PR TITLE
Test on Rails 5.2

### PR DESCRIPTION
**Pull request by swrobel**

### CODE REVIEW

**Comment by swrobel** [comment]
That's unfortunate. just pushed an update.

**Comment by antstorm** [comment]
@swrobel judging by the TravisCI output — shorthand versions in exclusion matrix also fails, running unsupported version combinations and failing the specs. I wish it worked, though…

**Comment by swrobel** [comment]
ok, third time's the charm!

**Comment by antstorm** [comment]
@swrobel all looks good now, thank you!

**Pull request merged**
