### PR TITLE
Monetize test matcher improvement

### PR DESCRIPTION
**Pull request by ILoGM**
I had a trouble with test helper. It didn't allow me to use ruble as default currency because helper was designed to use hardcoded '_cents' postfix. So, I've fixed it.

### CODE REVIEW

**Comment by semmons99** [comment]
Unfortunately this breaks a number of different builds. Please check TravisCI and fix the issue.

**Comment by ILoGM** [comment]
Yep, I see, I'll fix this.

**Comment by greggroth** [comment]
How's this going?

**Comment by ILoGM** [comment]
Oh, I'm so sorry! We've released our 8 month work recently so that I just don't have enough time. But I was about to fix it last week =)

**Comment by semmons99** [comment]
No activity in in over 4 weeks. Closing.

**Pull request closed without merging**
