### PR TITLE
make humanized_money helper respect currency decimal mark and thousan…

### LINKED ISSUE #410: "humanized_money" doesn't honor decimal mark and thousands separator of currency
```ruby
m = Money.new(123456, 'EUR')
m.currency.decimal_mark # ","
m.currency.thousands_separator # "."

include MoneyRails::ActionViewExtension
humanized_money_with_symbol m # "€1,234.56"
```

I would have expected `€1.234,56`, i.e. with the decimal mark and thousands separator according to the currency config.

### PR DESCRIPTION
**Pull request by manuelmeurer**
…ds separator

Fixes #410

### CODE REVIEW

**Comment by semmons99** [comment]
I18n doesn't take care of this or conflict?

**Comment by manuelmeurer** [comment]
@semmons99 Sorry, I don't understand what you mean by that.

**Comment by semmons99** [comment]
Does the i18n gem handle this already?

- shane

**Comment by manuelmeurer** [comment]
I don't see how the I18n gem is involved in this. The `humanized_money` helper calls `#format` on the Money instance.

**Comment by semmons99** [comment]
and #format understands i18n

- shane

**Comment by manuelmeurer** [comment]
I see. Still, the behaviour described in #410 seems unexpected. My suggested fix is in this PR. Whether this should be handled by I18n instead, I don't know.

**Comment by antstorm** [comment]
@manuelmeurer can you please fix the UTF-8 issue with Ruby 1.9.3? Check Travis log for more info.

**Comment by manuelmeurer** [comment]
@antstorm Done!

**Comment by semmons99** [comment]
Merged. Sorry it took so long.

**Comment by manuelmeurer** [comment]
No problem, thanks for merging! :+1:

**Comment by manuelmeurer** [comment]
Could you release v1.6.1? :smile:

**Comment by manuelmeurer** [comment]
ping! :smile_cat:

**Comment by antstorm** [comment]
@manuelmeurer sorry for a delay, `1.6.1` is now available on RubyGems

**Pull request merged**
