### PR TITLE
Ruby 3 support

### LINKED ISSUE #612: `t.monetize :price` raises an error on Ruby 3.0.0 Preview 1
I'm not sure if this is a Ruby 3.0.0 error and I just wanna let you know.

So I'm testing my app on Ruby 3.0.0 Preview 1 and it raises the error.
```
wrong number of arguments (given 3, expected 2)
``` 
When using:
```
t.monetize :price
```
Temporary solution:
```
t.integer :price_cents, default: 0, null: false
t.string :price_currency, default: MoneyRails.default_currency.to_s, null: false
```

### PR DESCRIPTION
**Pull request by juanmanuelramallo**
Resolves #612

Add ruby-3.0.0 as part of the CI

### CODE REVIEW

**Comment by juanmanuelramallo** [comment]
I can't get ruby-3.0.0 to work on Travis; somehow I'm asked to fetch the public key from RVM:

```
GPG signature verification failed for '/home/travis/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:
    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
or if it fails:
    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
the key can be compared with:
    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
```

**Comment by griffero** [comment]
is this going to work given #601?

**Comment by juanmanuelramallo** [comment]
It worked locally, on both ruby 3 and rails 6.1. 

Maybe the deprecation from #601 was deferred to the next minor version (?)

**Comment by juanmanuelramallo** [comment]
Hey @antstorm do you have any idea on how to fix Travis to correctly run ruby 3?

Or any ideas on how to move forward?

cc maintainers: @alup @semmons99 @weppos

**Comment by semmons99** [comment]
which travis-ci.org shutting down, they just may not support Ruby 3 right now. We should probably create a branch that migrates us to travis-ci.com

I will work on that today

**Comment by juanmanuelramallo** [comment]
It seems like you'll need to submit a request to (new) Travis to get unlimitted free minutes (for open source)

Btw, have you considered github actions?

**Comment by semmons99** [comment]
@juanmanuelramallo we are on the same wavelength. I plan on ditching Travis.CI for GH Actions. Just proved it out on RubyMoney/money-collections

**Comment by juanmanuelramallo** [comment]
That's great! 

Let me know if I can be of any assistance, a few months ago we set up a similar test matrix in GA for a gem https://github.com/rootstrap/yaaf/blob/master/.github/workflows/ci.yml#L10 and it has worked just fine so far (although obviously our gem has far less usage/contributions than money-rails)

**Comment by antstorm** [comment]
@juanmanuelramallo sorry for the delay here. Love the idea of using GA for this, @semmons99 do let us know how it goes

**Comment by antstorm** [comment]
@juanmanuelramallo in terms of the changes themselves — double splat was introduced back in 2.0, so it might be better to turn 1.9.3 into an exception (which we'll drop soon) than special-casing 3.0. Let me know what do you think

**Comment by juanmanuelramallo** [comment]
Perfect, sounds good to me

Please feel free to add more commits in here or just close this PR. Otherwise, I'll try to update it in the weekend to implement your suggestion about turning 1.9.3 into the exception rather than 3.0.0.

**Comment by semmons99** [comment]
@juanmanuelramallo I have updated the project to use GitHub Actions now. Would you mind updating this PR, or creating a new one, that enables 3.0 to work?

**Comment by juanmanuelramallo** [comment]
Hey @semmons99, that's amazing.

I noticed we are only testing on ruby-2.6 and ruby-2.7, does this mean the gem is dropping support for 1.9.8?

**Comment by semmons99** [comment]
> Hey @semmons99, that's amazing.
> 
> I noticed we are only testing on ruby-2.6 and ruby-2.7, does this mean the gem is dropping support for 1.9.8?

not officially. if it blocks 3.0 support yes. I just wanted to get GitHub actions working and getting 1.9 running is a bit of a pain

**Comment by juanmanuelramallo** [comment]
[This commit ](https://github.com/RubyMoney/money-rails/pull/617/commits/8611ea5e613ed2792b7b48995b4e63f742c8d673) won't work on 1.9.8 I believe

**Comment by semmons99** [comment]
what specifically cannot work in 1.9 with this specified commit @juanmanuelramallo ?

**Comment by juanmanuelramallo** [comment]
There is no double splat operator in ruby 1.9.x

**Comment by juanmanuelramallo** [comment]
To support both 1.9.3 and >2.6 (including 3.0.0) versions we'll need to:

1. Follow @antstorm 's approach https://github.com/RubyMoney/money-rails/pull/617#issuecomment-756125540 and have specific ruby files for ruby-1.9
2. Add ruby-1.9 to the CI otherwise there's no way for us to know it's working as expected

**Comment by semmons99** [comment]
@antstorm I am okay dropping support for Ruby below 2.6 and rolling a new major version. Our existing versions are robust and stable for the <2.6 crowd. Thoughts?

**Comment by F-3r** [comment]
Hey Folks :wave: Anything missing to move this forward? Anything I can do to help?
I would love to see this merged and use an officially released version

**Review by semmons99 — APPROVED** [review]

**Comment by semmons99** [comment]
@F-3r pinging me to remember was all. thanks. merging.

**Pull request merged**
