### PR TITLE
Build runs against Rails5

### PR DESCRIPTION
**Pull request by sivagollapalli**

### CODE REVIEW

**Comment by antstorm** [comment]
@sivagollapalli you've got a syntax error in your PR. Should be `rails50` instead of `rails5.0`

**Comment by antstorm** [comment]
@sivagollapalli any chance you can fix this?

**Comment by sivagollapalli** [comment]
@antstorm I have fixed. But looks like mongoid related specs are not running on travis. Is that an issue or intentional ?

**Comment by sivagollapalli** [comment]
@antstorm oops.. I overlooked mongoid builds.

**Comment by antstorm** [comment]
@sivagollapalli looking good, thanks for a PR!

**Pull request merged**
