### PR TITLE
Add support for PG and Rails 4.2

### PR DESCRIPTION
**Pull request by simonoff**
Fix for "Rails 4.2 Migration helper raises wrong number of argument error" #264

### CODE REVIEW

**Comment by Adam89** [comment]
@simonoff thanks for taking the time to create a pr for this :+1:

**Comment by semmons99** [comment]
Build is failing. Please fix so we can merge. Thanks!

**Comment by simonoff** [comment]
@semmons99 failed mongoid builds and related to database_cleaner gem.
```
/home/travis/build/RubyMoney/money-rails/gemfiles/vendor/bundle/ruby/1.9.1/gems/database_cleaner-1.4.0/lib/database_cleaner/base.rb:139:in `rescue in orm_strategy': The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)
```

**Comment by simonoff** [comment]
@semmons99 fixed. But i think need to rewrite tests to support different databases.

**Comment by semmons99** [comment]
excellent!

**Pull request merged**
