### PR TITLE
Refactor the monetizable function

### PR DESCRIPTION
**Pull request by GCorbel**
PR for issue #394 

I did a refactoring. Basically, I extracted the long monetizable function in smaller objects. This is a just a proposition. There is probably other ways to do it. Please let me know what you think. 

If you agree, I will move specs to be unitary.

Thanks for very reliable tests.

### CODE REVIEW

**Comment by semmons99** [comment]
I'm fine doing this. But it's a very large change. You need to ensure no new edge cases or bugs have been created by it.

**Comment by GCorbel** [comment]
All tests are passing. I look at some possible use cases and I don't see what can be wrong. Can you give it a try?

**Comment by antstorm** [comment]
I agree with @semmons99 on this one — huge change, but no new unit tests. All the new classes need to be properly tested in isolation.

Couple of other comments:

- Use `attr_reader`s instead of `attr_accessor`s, since you're not using setters
- `ModelExtensions` namespace is very misleading, since none of the included classes are actually extending model
- It seems that you've taken the "service"-object approach for `AttributeReader`, `AttributeWriter` and `CurrencyFinder`, but `MonetizableAttribute` is quite a different one, which makes it a bit confusing. Especially considering that they all live under the same namespace
- `AttributeReader`, `AttributeWriter` and `CurrencyFinder` can definitely share a common initializer for setting `model` and `name` attributes.

**Comment by GCorbel** [comment]
@antstorm I agree with test in isolation but there is no new unit tests because there is no new behaviour.

I agree for other comments and will update my code.

Do you it's useful to continue this PR or it has no chance to be merged because it's a too big change?

**Comment by antstorm** [comment]
@GCorbel yes, there's no new behaviour from the external API point of view, but there are now many more moving parts internally. This actually makes the whole thing much easier to test, which is really good.

I think that the best approach here would be to take this PR and split it into multiple ones (I guess 4 is the right number here, one per each new class and as a matter of fact — per each commit), each focusing on refactoring one part and new set of tests.

If you need help with writing tests — feel free to give me a shout. And btw, great work!

**Comment by rafeDraper** [comment]
Hello @antstorm, I would like to contribute to this issue, since the last interaction is almost 4 years old, I would like to know if there is any update in it since there is an actual solution already committed.  I would like to begin by splitting them as mentioned in 4, and test them accordingly. 

@GCorbel (Great work!)

**Comment by antstorm** [comment]
@rafeDraper help is always appreciated!

There's a half way solution in place to reduce the complexity in some of these methods, but nothing long term. The approach I had in mind was to move most of the logic into an initializable object and reduce the logic within the model itself down to interaction with that object. It needs further digging to figure out whether that actually works.

If you wanna start working on this — I'm happy to give you early feedback, so we can align on the best solution.

**Comment by rafeDraper** [comment]
@antstorm Sure, I would love to contribute and help. Let me know how I can get more feedback on it.

**Pull request closed without merging**
