### PR TITLE
Bump monetize for coinbase compatibility

### PR DESCRIPTION
**Pull request by saizai**
money-rails (>= 1.4.1) ruby depends on
      monetize (~> 1.1.0) ruby

    coinbase (>= 2.2.1) ruby depends on
      monetize (~> 1.3) ruby

### CODE REVIEW

**Comment by saizai** [comment]
(Also, bump gem)

**Comment by semmons99** [comment]
@RubyMoney/money-rails-devs build is failing after this. Ideas Why/

**Comment by saizai** [comment]
@semmons99 Looks like it's because MongoDB won't allow nils, and your test wants it to. I don't know MongoDB enough to debug further than that though.

**Comment by semmons99** [comment]
No activity in in over 4 weeks. Closing.

**Comment by saizai** [comment]
… is it fixed?

If not, it should stay open as an issue.

**Comment by semmons99** [comment]
With the RubyMoney org, we consider it a non-priority if an issue or pull request has gone silent after 4 weeks. It is welcome to reopen when you are someone else picks up the reigns and moves it forward again.

**Pull request closed without merging**
