### PR TITLE
Split monetize method apart

### PR DESCRIPTION
**Pull request by antstorm**
Hey all,

This is my attempt at refactoring the monetize method by breaking down all dynamically generated methods into simple calls to static methods. I think that dynamic methods is a bad pattern that people keep abusing by adding more context-wrapped variables.

I've also included quite a lot of tests to make sure these newly introduced methods do exactly what we expect from them.

### CODE REVIEW

**Comment by antstorm** [comment]
Sorry for a duplicate PR, Travis didn't pick the first one up for some reason.

**Comment by igneus** [comment]
Is this going to be merged any soon? If so, I would wait for it before proposing a fix to #399 .

**Comment by antstorm** [comment]
@igneus hopefully… need someone to take a look at this one first

**Comment by antstorm** [comment]
Failing tests should be fixed by #431

**Pull request merged**
